apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
        env: dev
    spec:
      containers:
      - name: flask
        image: uniper.azurecr.io/python-flask
        containerPort: 8080
        protocol: TCP
